name: Docker Image CI

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3\

      - name: Checkout external repository
        uses: actions/checkout@v3
        with:
          ref: master
          repository: mac-lucky/Kubernetes
          path: k8s
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Copy file from external repository
        run: |
          cp k8s/portfolio-wiktoria/portfolio-app.yml .github/manifests/portfolio-app.yml

      - name: Commit changes
        run: |
          git config --global user.email "maciejkedziora98@gmail.com"
          git config --global user.name "mac-lucky"
          git add .github/manifests/portfolio-app.yml
          git commit -m "Updating file from external repository"
          git push origin master

      - name: Delete the folder k8s
        run: |
          rm -rf k8s
        
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV 

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: maclucky/ux-ui-site
          tags: |
            type=raw,value={{date 'YYYYMMDDHHmm'}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 

      - name: Run script to replace version in manifest
        run: ./.github/scripts/deployment.sh $NOW
        shell: bash

      - name: Update manifest for landingpage
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '.github/manifests/portfolio-app.yml'
          destination_repo: 'mac-lucky/Kubernetes'
          destination_folder: 'portfolio-wiktoria'
          user_email: 'maciejkedziora98@gmail.com'
          user_name: 'mac-lucky'
          destination_branch: 'master'
          commit_message: 'Update app version'
