name: Docker Image CI

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-push:
    uses: mac-lucky/actions-shared-workflows/.github/workflows/docker-cicd-reusable.yml@master
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      app_name: ux-ui-site
      dockerhub_image: maclucky/ux-ui-site
      ghcr_image: ghcr.io/mac-lucky/ux-ui-site
      push_to_dockerhub: true
      enable_security_scan: true
      platforms: linux/amd64,linux/arm64
